window.esdocSearchIndex = [
  [
    "documentor/react_redux/constants.jsx~apexrest_proxy",
    "variable/index.html#static-variable-APEXREST_PROXY",
    "<span>APEXREST_PROXY</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/containers/addnewgraph.jsx~addnewgraph",
    "function/index.html#static-function-AddNewGraph",
    "<span>AddNewGraph</span> <span class=\"search-result-import-path\">Documentor/React_Redux/containers/AddNewGraph.jsx</span>",
    "function"
  ],
  [
    "documentor/react_redux/constants.jsx~cancel",
    "variable/index.html#static-variable-CANCEL",
    "<span>CANCEL</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/constants.jsx~cancel_editing",
    "variable/index.html#static-variable-CANCEL_EDITING",
    "<span>CANCEL_EDITING</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/constants.jsx~checkbox_1",
    "variable/index.html#static-variable-CHECKBOX_1",
    "<span>CHECKBOX_1</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/constants.jsx~checkbox_2",
    "variable/index.html#static-variable-CHECKBOX_2",
    "<span>CHECKBOX_2</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/constants.jsx~checkbox_3",
    "variable/index.html#static-variable-CHECKBOX_3",
    "<span>CHECKBOX_3</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/constants.jsx~checkbox_4",
    "variable/index.html#static-variable-CHECKBOX_4",
    "<span>CHECKBOX_4</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/constants.jsx~checkbox_group_header",
    "variable/index.html#static-variable-CHECKBOX_GROUP_HEADER",
    "<span>CHECKBOX_GROUP_HEADER</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/constants.jsx~choose_graph",
    "variable/index.html#static-variable-CHOOSE_GRAPH",
    "<span>CHOOSE_GRAPH</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/constants.jsx~choose_report",
    "variable/index.html#static-variable-CHOOSE_REPORT",
    "<span>CHOOSE_REPORT</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/constants.jsx~create_graph",
    "variable/index.html#static-variable-CREATE_GRAPH",
    "<span>CREATE_GRAPH</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/constants.jsx~create_graph_complete",
    "variable/index.html#static-variable-CREATE_GRAPH_COMPLETE",
    "<span>CREATE_GRAPH_COMPLETE</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/constants.jsx~create_graph_error",
    "variable/index.html#static-variable-CREATE_GRAPH_ERROR",
    "<span>CREATE_GRAPH_ERROR</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/constants.jsx~delete",
    "variable/index.html#static-variable-DELETE",
    "<span>DELETE</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/constants.jsx~delete_graph",
    "variable/index.html#static-variable-DELETE_GRAPH",
    "<span>DELETE_GRAPH</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/constants.jsx~delete_graph_complete",
    "variable/index.html#static-variable-DELETE_GRAPH_COMPLETE",
    "<span>DELETE_GRAPH_COMPLETE</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/constants.jsx~delete_graph_error",
    "variable/index.html#static-variable-DELETE_GRAPH_ERROR",
    "<span>DELETE_GRAPH_ERROR</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/constants.jsx~edit",
    "variable/index.html#static-variable-EDIT",
    "<span>EDIT</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/constants.jsx~edit_graph",
    "variable/index.html#static-variable-EDIT_GRAPH",
    "<span>EDIT_GRAPH</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/constants.jsx~error_message",
    "variable/index.html#static-variable-ERROR_MESSAGE",
    "<span>ERROR_MESSAGE</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/constants.jsx~graph",
    "variable/index.html#static-variable-GRAPH",
    "<span>GRAPH</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/constants.jsx~id",
    "variable/index.html#static-variable-ID",
    "<span>ID</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/constants.jsx~loading",
    "variable/index.html#static-variable-LOADING",
    "<span>LOADING</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/constants.jsx~load_graphs",
    "variable/index.html#static-variable-LOAD_GRAPHS",
    "<span>LOAD_GRAPHS</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/constants.jsx~load_graphs_complete",
    "variable/index.html#static-variable-LOAD_GRAPHS_COMPLETE",
    "<span>LOAD_GRAPHS_COMPLETE</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/constants.jsx~load_graphs_error",
    "variable/index.html#static-variable-LOAD_GRAPHS_ERROR",
    "<span>LOAD_GRAPHS_ERROR</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/constants.jsx~load_graph_types",
    "variable/index.html#static-variable-LOAD_GRAPH_TYPES",
    "<span>LOAD_GRAPH_TYPES</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/constants.jsx~load_graph_types_complete",
    "variable/index.html#static-variable-LOAD_GRAPH_TYPES_COMPLETE",
    "<span>LOAD_GRAPH_TYPES_COMPLETE</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/constants.jsx~load_graph_types_error",
    "variable/index.html#static-variable-LOAD_GRAPH_TYPES_ERROR",
    "<span>LOAD_GRAPH_TYPES_ERROR</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/constants.jsx~load_reports",
    "variable/index.html#static-variable-LOAD_REPORTS",
    "<span>LOAD_REPORTS</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/constants.jsx~load_reports_complete",
    "variable/index.html#static-variable-LOAD_REPORTS_COMPLETE",
    "<span>LOAD_REPORTS_COMPLETE</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/constants.jsx~load_reports_error",
    "variable/index.html#static-variable-LOAD_REPORTS_ERROR",
    "<span>LOAD_REPORTS_ERROR</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/constants.jsx~modal_button_create",
    "variable/index.html#static-variable-MODAL_BUTTON_CREATE",
    "<span>MODAL_BUTTON_CREATE</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/constants.jsx~modal_button_update",
    "variable/index.html#static-variable-MODAL_BUTTON_UPDATE",
    "<span>MODAL_BUTTON_UPDATE</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/constants.jsx~modal_header",
    "variable/index.html#static-variable-MODAL_HEADER",
    "<span>MODAL_HEADER</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/constants.jsx~new",
    "variable/index.html#static-variable-NEW",
    "<span>NEW</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/constants.jsx~new_graph",
    "variable/index.html#static-variable-NEW_GRAPH",
    "<span>NEW_GRAPH</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/constants.jsx~param_name_action",
    "variable/index.html#static-variable-PARAM_NAME_ACTION",
    "<span>PARAM_NAME_ACTION</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/constants.jsx~param_value_graphtype",
    "variable/index.html#static-variable-PARAM_VALUE_GRAPHTYPE",
    "<span>PARAM_VALUE_GRAPHTYPE</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/constants.jsx~param_value_retrieve_graph",
    "variable/index.html#static-variable-PARAM_VALUE_RETRIEVE_GRAPH",
    "<span>PARAM_VALUE_RETRIEVE_GRAPH</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/constants.jsx~param_value_retrieve_graphs",
    "variable/index.html#static-variable-PARAM_VALUE_RETRIEVE_GRAPHS",
    "<span>PARAM_VALUE_RETRIEVE_GRAPHS</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/constants.jsx~preview_header",
    "variable/index.html#static-variable-PREVIEW_HEADER",
    "<span>PREVIEW_HEADER</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/constants.jsx~ready",
    "variable/index.html#static-variable-READY",
    "<span>READY</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/constants.jsx~refresh_graph",
    "variable/index.html#static-variable-REFRESH_GRAPH",
    "<span>REFRESH_GRAPH</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/constants.jsx~refresh_graph_complete",
    "variable/index.html#static-variable-REFRESH_GRAPH_COMPLETE",
    "<span>REFRESH_GRAPH_COMPLETE</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/constants.jsx~refresh_graph_error",
    "variable/index.html#static-variable-REFRESH_GRAPH_ERROR",
    "<span>REFRESH_GRAPH_ERROR</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/constants.jsx~report",
    "variable/index.html#static-variable-REPORT",
    "<span>REPORT</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/constants.jsx~report_api",
    "variable/index.html#static-variable-REPORT_API",
    "<span>REPORT_API</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/constants.jsx~report_api_describe",
    "variable/index.html#static-variable-REPORT_API_DESCRIBE",
    "<span>REPORT_API_DESCRIBE</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/constants.jsx~report_api_query",
    "variable/index.html#static-variable-REPORT_API_QUERY",
    "<span>REPORT_API_QUERY</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/constants.jsx~retrieve_graphs",
    "variable/index.html#static-variable-RETRIEVE_GRAPHS",
    "<span>RETRIEVE_GRAPHS</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/constants.jsx~retrieve_report_data",
    "variable/index.html#static-variable-RETRIEVE_REPORT_DATA",
    "<span>RETRIEVE_REPORT_DATA</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/constants.jsx~retrieve_report_data_complete",
    "variable/index.html#static-variable-RETRIEVE_REPORT_DATA_COMPLETE",
    "<span>RETRIEVE_REPORT_DATA_COMPLETE</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/constants.jsx~retrieve_report_data_error",
    "variable/index.html#static-variable-RETRIEVE_REPORT_DATA_ERROR",
    "<span>RETRIEVE_REPORT_DATA_ERROR</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/constants.jsx~retrieve_report_metadata",
    "variable/index.html#static-variable-RETRIEVE_REPORT_METADATA",
    "<span>RETRIEVE_REPORT_METADATA</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/constants.jsx~retrieve_report_metadata_complete",
    "variable/index.html#static-variable-RETRIEVE_REPORT_METADATA_COMPLETE",
    "<span>RETRIEVE_REPORT_METADATA_COMPLETE</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/constants.jsx~retrieve_report_metadata_error",
    "variable/index.html#static-variable-RETRIEVE_REPORT_METADATA_ERROR",
    "<span>RETRIEVE_REPORT_METADATA_ERROR</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/constants.jsx~update",
    "variable/index.html#static-variable-UPDATE",
    "<span>UPDATE</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/constants.jsx~update_graph",
    "variable/index.html#static-variable-UPDATE_GRAPH",
    "<span>UPDATE_GRAPH</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/constants.jsx~update_graph_complete",
    "variable/index.html#static-variable-UPDATE_GRAPH_COMPLETE",
    "<span>UPDATE_GRAPH_COMPLETE</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/constants.jsx~update_graph_error",
    "variable/index.html#static-variable-UPDATE_GRAPH_ERROR",
    "<span>UPDATE_GRAPH_ERROR</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/constants.jsx~update_graph_preview",
    "variable/index.html#static-variable-UPDATE_GRAPH_PREVIEW",
    "<span>UPDATE_GRAPH_PREVIEW</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/constants.jsx~update_report_preview",
    "variable/index.html#static-variable-UPDATE_REPORT_PREVIEW",
    "<span>UPDATE_REPORT_PREVIEW</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/constants.jsx~view",
    "variable/index.html#static-variable-VIEW",
    "<span>VIEW</span> <span class=\"search-result-import-path\">Documentor/React_Redux/constants.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/containers/viewgraphs.jsx~visiblegraphs",
    "variable/index.html#static-variable-VisibleGraphs",
    "<span>VisibleGraphs</span> <span class=\"search-result-import-path\">Documentor/React_Redux/containers/ViewGraphs.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/reducers/ajaxmiddleware.jsx~ajaxmiddleware",
    "function/index.html#static-function-ajaxMiddleware",
    "<span>ajaxMiddleware</span> <span class=\"search-result-import-path\">Documentor/React_Redux/reducers/ajaxMiddleware.jsx</span>",
    "function"
  ],
  [
    "documentor/react_redux/components/dashboard.jsx~buildgraphs",
    "function/index.html#static-function-buildGraphs",
    "<span>buildGraphs</span> <span class=\"search-result-import-path\">Documentor/React_Redux/components/Dashboard.jsx</span>",
    "function"
  ],
  [
    "documentor/react_redux/libs/utils.jsx~buildinstance",
    "function/index.html#static-function-buildInstance",
    "<span>buildInstance</span> <span class=\"search-result-import-path\">Documentor/React_Redux/libs/utils.jsx</span>",
    "function"
  ],
  [
    "documentor/react_redux/libs/utils.jsx~buildparams",
    "function/index.html#static-function-buildParams",
    "<span>buildParams</span> <span class=\"search-result-import-path\">Documentor/React_Redux/libs/utils.jsx</span>",
    "function"
  ],
  [
    "documentor/react_redux/libs/utils.jsx~buildrequest",
    "function/index.html#static-function-buildRequest",
    "<span>buildRequest</span> <span class=\"search-result-import-path\">Documentor/React_Redux/libs/utils.jsx</span>",
    "function"
  ],
  [
    "documentor/react_redux/actions.jsx~cancelediting",
    "function/index.html#static-function-cancelEditing",
    "<span>cancelEditing</span> <span class=\"search-result-import-path\">Documentor/React_Redux/actions.jsx</span>",
    "function"
  ],
  [
    "documentor/react_redux/actions.jsx~creategraph",
    "function/index.html#static-function-createGraph",
    "<span>createGraph</span> <span class=\"search-result-import-path\">Documentor/React_Redux/actions.jsx</span>",
    "function"
  ],
  [
    "documentor/react_redux/libs/ajax.jsx~deleteapexrest",
    "function/index.html#static-function-deleteApexREST",
    "<span>deleteApexREST</span> <span class=\"search-result-import-path\">Documentor/React_Redux/libs/ajax.jsx</span>",
    "function"
  ],
  [
    "documentor/react_redux/actions.jsx~deletegraph",
    "function/index.html#static-function-deleteGraph",
    "<span>deleteGraph</span> <span class=\"search-result-import-path\">Documentor/React_Redux/actions.jsx</span>",
    "function"
  ],
  [
    "documentor/react_redux/actions.jsx~editgraph",
    "function/index.html#static-function-editGraph",
    "<span>editGraph</span> <span class=\"search-result-import-path\">Documentor/React_Redux/actions.jsx</span>",
    "function"
  ],
  [
    "documentor/react_redux/libs/ajax.jsx~fetchapexrest",
    "function/index.html#static-function-fetchApexREST",
    "<span>fetchApexREST</span> <span class=\"search-result-import-path\">Documentor/React_Redux/libs/ajax.jsx</span>",
    "function"
  ],
  [
    "documentor/react_redux/libs/ajax.jsx~fetchreportapi",
    "function/index.html#static-function-fetchReportAPI",
    "<span>fetchReportAPI</span> <span class=\"search-result-import-path\">Documentor/React_Redux/libs/ajax.jsx</span>",
    "function"
  ],
  [
    "documentor/react_redux/libs/utils.jsx~generateguid",
    "function/index.html#static-function-generateGUID",
    "<span>generateGUID</span> <span class=\"search-result-import-path\">Documentor/React_Redux/libs/utils.jsx</span>",
    "function"
  ],
  [
    "documentor/react_redux/reducers/graphtypes.jsx~graphtypes",
    "function/index.html#static-function-graphTypes",
    "<span>graphTypes</span> <span class=\"search-result-import-path\">Documentor/React_Redux/reducers/graphTypes.jsx</span>",
    "function"
  ],
  [
    "documentor/react_redux/reducers/graphs.jsx~graphs",
    "function/index.html#static-function-graphs",
    "<span>graphs</span> <span class=\"search-result-import-path\">Documentor/React_Redux/reducers/graphs.jsx</span>",
    "function"
  ],
  [
    "documentor/react_redux/reducers/mode.jsx~mode",
    "function/index.html#static-function-mode",
    "<span>mode</span> <span class=\"search-result-import-path\">Documentor/React_Redux/reducers/mode.jsx</span>",
    "function"
  ],
  [
    "documentor/react_redux/reducers/session.jsx~mode",
    "function/index.html#static-function-mode",
    "<span>mode</span> <span class=\"search-result-import-path\">Documentor/React_Redux/reducers/session.jsx</span>",
    "function"
  ],
  [
    "documentor/react_redux/actions.jsx~newgraph",
    "function/index.html#static-function-newGraph",
    "<span>newGraph</span> <span class=\"search-result-import-path\">Documentor/React_Redux/actions.jsx</span>",
    "function"
  ],
  [
    "documentor/react_redux/libs/ajax.jsx~postapexrest",
    "function/index.html#static-function-postApexREST",
    "<span>postApexREST</span> <span class=\"search-result-import-path\">Documentor/React_Redux/libs/ajax.jsx</span>",
    "function"
  ],
  [
    "documentor/react_redux/libs/ajax.jsx~postreportapi",
    "function/index.html#static-function-postReportAPI",
    "<span>postReportAPI</span> <span class=\"search-result-import-path\">Documentor/React_Redux/libs/ajax.jsx</span>",
    "function"
  ],
  [
    "documentor/react_redux/libs/ajax.jsx~putapexrest",
    "function/index.html#static-function-putApexREST",
    "<span>putApexREST</span> <span class=\"search-result-import-path\">Documentor/React_Redux/libs/ajax.jsx</span>",
    "function"
  ],
  [
    "documentor/react_redux/reducers/index.jsx~reducers",
    "variable/index.html#static-variable-reducers",
    "<span>reducers</span> <span class=\"search-result-import-path\">Documentor/React_Redux/reducers/index.jsx</span>",
    "variable"
  ],
  [
    "documentor/react_redux/actions.jsx~refreshdashboard",
    "function/index.html#static-function-refreshDashboard",
    "<span>refreshDashboard</span> <span class=\"search-result-import-path\">Documentor/React_Redux/actions.jsx</span>",
    "function"
  ],
  [
    "documentor/react_redux/actions.jsx~refreshgraph",
    "function/index.html#static-function-refreshGraph",
    "<span>refreshGraph</span> <span class=\"search-result-import-path\">Documentor/React_Redux/actions.jsx</span>",
    "function"
  ],
  [
    "documentor/react_redux/actions.jsx~retrievegraphtypes",
    "function/index.html#static-function-retrieveGraphTypes",
    "<span>retrieveGraphTypes</span> <span class=\"search-result-import-path\">Documentor/React_Redux/actions.jsx</span>",
    "function"
  ],
  [
    "documentor/react_redux/actions.jsx~retrievegraphs",
    "function/index.html#static-function-retrieveGraphs",
    "<span>retrieveGraphs</span> <span class=\"search-result-import-path\">Documentor/React_Redux/actions.jsx</span>",
    "function"
  ],
  [
    "documentor/react_redux/actions.jsx~retrievereportdata",
    "function/index.html#static-function-retrieveReportData",
    "<span>retrieveReportData</span> <span class=\"search-result-import-path\">Documentor/React_Redux/actions.jsx</span>",
    "function"
  ],
  [
    "documentor/react_redux/actions.jsx~retrievereportmetadata",
    "function/index.html#static-function-retrieveReportMetaData",
    "<span>retrieveReportMetaData</span> <span class=\"search-result-import-path\">Documentor/React_Redux/actions.jsx</span>",
    "function"
  ],
  [
    "documentor/react_redux/actions.jsx~retrievereports",
    "function/index.html#static-function-retrieveReports",
    "<span>retrieveReports</span> <span class=\"search-result-import-path\">Documentor/React_Redux/actions.jsx</span>",
    "function"
  ],
  [
    "documentor/react_redux/actions.jsx~updategraph",
    "function/index.html#static-function-updateGraph",
    "<span>updateGraph</span> <span class=\"search-result-import-path\">Documentor/React_Redux/actions.jsx</span>",
    "function"
  ],
  [
    "documentor/react_redux/actions.jsx~updategraphid",
    "function/index.html#static-function-updateGraphId",
    "<span>updateGraphId</span> <span class=\"search-result-import-path\">Documentor/React_Redux/actions.jsx</span>",
    "function"
  ],
  [
    "documentor/react_redux/actions.jsx~updatereportid",
    "function/index.html#static-function-updateReportId",
    "<span>updateReportId</span> <span class=\"search-result-import-path\">Documentor/React_Redux/actions.jsx</span>",
    "function"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "https://developer.mozilla.org/en/docs/Web/API/AudioContext",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "https://developer.mozilla.org/en-US/docs/Web/API/Element",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "https://developer.mozilla.org/en-US/docs/Web/API/Event",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "https://developer.mozilla.org/en-US/docs/Web/API/Node",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "https://developer.mozilla.org/en-US/docs/Web/API/NodeList",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "https://developer.mozilla.org/en/docs/Web/API/XMLHttpRequest",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "react_redux/actions.jsx",
    "file/React_Redux/actions.jsx.html",
    "React_Redux/actions.jsx",
    "file"
  ],
  [
    "react_redux/components/button.jsx",
    "file/React_Redux/components/Button.jsx.html",
    "React_Redux/components/Button.jsx",
    "file"
  ],
  [
    "react_redux/components/dashboard.jsx",
    "file/React_Redux/components/Dashboard.jsx.html",
    "React_Redux/components/Dashboard.jsx",
    "file"
  ],
  [
    "react_redux/components/dropdown.jsx",
    "file/React_Redux/components/Dropdown.jsx.html",
    "React_Redux/components/Dropdown.jsx",
    "file"
  ],
  [
    "react_redux/components/error.jsx",
    "file/React_Redux/components/Error.jsx.html",
    "React_Redux/components/Error.jsx",
    "file"
  ],
  [
    "react_redux/components/graph.jsx",
    "file/React_Redux/components/Graph.jsx.html",
    "React_Redux/components/Graph.jsx",
    "file"
  ],
  [
    "react_redux/components/graphguide.jsx",
    "file/React_Redux/components/GraphGuide.jsx.html",
    "React_Redux/components/GraphGuide.jsx",
    "file"
  ],
  [
    "react_redux/components/header.jsx",
    "file/React_Redux/components/Header.jsx.html",
    "React_Redux/components/Header.jsx",
    "file"
  ],
  [
    "react_redux/components/icon.jsx",
    "file/React_Redux/components/Icon.jsx.html",
    "React_Redux/components/Icon.jsx",
    "file"
  ],
  [
    "react_redux/components/modal.jsx",
    "file/React_Redux/components/Modal.jsx.html",
    "React_Redux/components/Modal.jsx",
    "file"
  ],
  [
    "react_redux/constants.jsx",
    "file/React_Redux/constants.jsx.html",
    "React_Redux/constants.jsx",
    "file"
  ],
  [
    "react_redux/containers/addnewgraph.jsx",
    "file/React_Redux/containers/AddNewGraph.jsx.html",
    "React_Redux/containers/AddNewGraph.jsx",
    "file"
  ],
  [
    "react_redux/containers/viewgraphs.jsx",
    "file/React_Redux/containers/ViewGraphs.jsx.html",
    "React_Redux/containers/ViewGraphs.jsx",
    "file"
  ],
  [
    "react_redux/index.jsx",
    "file/React_Redux/index.jsx.html",
    "React_Redux/index.jsx",
    "file"
  ],
  [
    "react_redux/libs/ajax.jsx",
    "file/React_Redux/libs/ajax.jsx.html",
    "React_Redux/libs/ajax.jsx",
    "file"
  ],
  [
    "react_redux/libs/utils.jsx",
    "file/React_Redux/libs/utils.jsx.html",
    "React_Redux/libs/utils.jsx",
    "file"
  ],
  [
    "react_redux/node_modules/babel/test/fixtures/babel-node/require/in-files/not_node_modules.jsx",
    "file/React_Redux/node_modules/babel/test/fixtures/babel-node/require/in-files/not_node_modules.jsx.html",
    "React_Redux/node_modules/babel/test/fixtures/babel-node/require/in-files/not_node_modules.jsx",
    "file"
  ],
  [
    "react_redux/reducers/ajaxmiddleware.jsx",
    "file/React_Redux/reducers/ajaxMiddleware.jsx.html",
    "React_Redux/reducers/ajaxMiddleware.jsx",
    "file"
  ],
  [
    "react_redux/reducers/graphtypes.jsx",
    "file/React_Redux/reducers/graphTypes.jsx.html",
    "React_Redux/reducers/graphTypes.jsx",
    "file"
  ],
  [
    "react_redux/reducers/graphs.jsx",
    "file/React_Redux/reducers/graphs.jsx.html",
    "React_Redux/reducers/graphs.jsx",
    "file"
  ],
  [
    "react_redux/reducers/index.jsx",
    "file/React_Redux/reducers/index.jsx.html",
    "React_Redux/reducers/index.jsx",
    "file"
  ],
  [
    "react_redux/reducers/mode.jsx",
    "file/React_Redux/reducers/mode.jsx.html",
    "React_Redux/reducers/mode.jsx",
    "file"
  ],
  [
    "react_redux/reducers/session.jsx",
    "file/React_Redux/reducers/session.jsx.html",
    "React_Redux/reducers/session.jsx",
    "file"
  ]
]